language: node_js
jobs:
  include:
    - stage: test
      script:
        - npm run cover
        - cat ./build/coverage/lcov.info | npx coveralls
      node_js: 14.14.0
    - stage: doc
      node_js: lts/*
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        cleanup: 'false'
        script: npx semantic-release
branches:
  only:
    - master
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
